# Generated by Django 2.2.4 on 2019-11-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('standard', models.CharField(default='', max_length=50)),
                ('roll', models.IntegerField()),
                ('essay_topic', models.CharField(default='', max_length=100)),
                ('essay', models.TextField(default='')),
            ],
            options={
                'db_table': 'name',
                'managed': True,
            },
        ),
    ]
